version: '3'
services:
  moe:
    container_name: misaka
    image: docker-registry.yuri.moe/moegirl-ios-relay-server/image
    environment:
      PORT: 8888
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: "${MYSQL_USER}"
      DB_PASS: "${MYSQL_PASSWORD}"
      DB_NAME: "${MYSQL_DB_NAME}"
      API_URL: "${API_URL}"
      BACKEND_URL: "${BACKEND_URL}"
      CRAWLER_UA: "Moegirl iOS Proxy"
    volumes:
      - ./public_html:/usr/src/app/main
    ports:
      - ${PROXY_ADDRESS}:8888
    depends_on:
      - db
    restart: always
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_ABSOLUTE_URI: "${PMA_ABSOLUTE_URI}"
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - ${PMA_ADDRESS}:80
    links:
      - db:db
    depends_on:
      - db
    restart: always
  db:
    image: mysql:latest
    ports:
      - ${MYSQL_ADDRESS}:3306
    expose:
      - 3306
    command: [
      '--default_authentication_plugin=mysql_native_password',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_HOST: db:3306
      MYSQL_DATABASE: "${MYSQL_DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    restart: always


